### ISSUE TITLE
Plugins as ORAS

### ISSUE THREAD

**Issue by rasavant-ms** [cse-labs/ratify#50] opened 2022-11-21 18:38 UTC
**Description**
Using Plugins from ACR

**AC**
- Push a plugin to ACR
- Update Ratify to pull images via ORAS
   - At startup when using config.json
   - When registering a new plugin using CRD

**Comment by noelbundick-msft** [comment] 2022-12-06 22:27
If we want to pick this up, we should try it out, form some opinions, and then

* Post an Issue + join Ratify community call for discussion
* Close it out and decide not to carry this forward

**Comment by noelbundick-msft** [comment] 2022-12-14 04:17
Discussed at the 2022-12-13 community call, where it was supported. Decision is to move forward with an issue / design doc for tracking, and open a working draft PR based on the initial prototype to gather feedback & ideas

**Comment by noelbundick-msft** [comment] 2022-12-19 18:16
Primary goal: draft pr out for discussion by 2022-12-21

**Comment by mluker** [comment] 2023-01-17 13:10
Duplicate of #78

**Closed by mluker** 2023-01-17 13:10 UTC
Labels: enhancement, plugins
